
wifi_ssid: "YourWifi"
wifi_password: "YourPassword"

mqtt_venusos_host: "192.168.1.10"
mqtt_venusos_user: "user"
mqtt_venusos_pswd: "password"

mppt100_20_mac: "AA:BB:CC:DD:EE:FF"
mppt100_20_key: "xxxxxxxxxxxxxxxx"

smartshunt500a_mac: "AA:BB:CC:DD:EE:FF"
smartshunt500a_key: "xxxxxxxxxxxxxxxx"
